name: ServerHelper
main: ServerHelper\Main
version: 1.0.0
author: AMDISYES
api: 
- 1.0.0
- 2.0.0
- 3.0.0
- 3.0.0-ALPHA1
- 3.0.0-ALPHA2
- 3.0.0-ALPHA3
- 3.0.0-ALPHA4
- 3.0.0-ALPHA5
- 4.0.0
- 4.0.0-ALPHA1
- 4.0.0-ALPHA2
- 4.0.0-ALPHA3
- 4.0.0-ALPHA4
- 4.0.0-ALPHA5
load: STARTUP
commands:
  sh:
    description: "服务器帮助"
    permission: sh.command.player
  opsh:
    description: "OP帮助"
    permission: sh.command.op
permissions:
  sh.command:
    default: true
    children:
      sh.command.player:
        default: true
      sh.command.op:
        default: op